name: 'youpipe'
version: 0.0.1
#author: anthony bobenrieth anthony@bobenrieth.fr
#homepage: https://www.google.fr
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  polymer: ">=0.16.3+1 <0.17.0"
  paper_elements: ">=0.7.0 <0.8.0"
  googleapis_auth: any
  googleapis: ">=0.3.0 <0.5.0"
  http: '>=0.11.1 <0.12.0'
  crypto: '>=0.9.0 <0.10.0'
  _discoveryapis_commons: '>=0.1.0 <0.2.0'
  comid: "^0.0.4+5.2.1"
  appengine: ">=0.2.1 <0.3.0"
  endpoints: "^0.1.0"
transformers:
- polymer:
    entry_points: web/main.html
